name: Build Pull Request
on: pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-artifacts
          path: build/libs
